### ISSUE TITLE
TypeError: _cookie_js2.default.get is not a function

### ISSUE THREAD

**Issue by griffinmichl** [10clouds/cyclejs-cookie#1]
Can't seem to get this driver working. The example in the README throws this error.

**Comment by wiktor-obrebski** [comment]
can you tell me more about this error? I just run this example on more or less clean environment and this work fine for me. I need more details.

**Comment by wiktor-obrebski** [comment]
it looks like you have not installed `cookie_js` dependency.
it's required by this package `package.json` file and should be automatically installed if you use
`npm install cyclejs-cookie` command. can you check if it is located in your `node_modules` directory?

**Comment by wiktor-obrebski** [comment]
second option is that you just need to add it as direct dependency to your `index.html` file (it is case when you don't use webpack or have it configured incorrectly)

**Comment by savuori** [comment]
I have the same problem. There seems to be problem with brunch, switching to webpack made the error go away without any other changes.

**Comment by wiktor-obrebski** [comment]
@savuori just published new version where I use my fork of cookie_js library. problem have source in way how `cookie_js` export it's api - it's work a little diffrent for CommonJS and AMD system.

I create PR for library creator here, but `10clouds/cyclejs-cookie` use my local fork temporary, so it should work properly.
https://github.com/florian/cookie.js/pull/39

Let me know if it fixed the problem for you.

**Comment by wiktor-obrebski** [comment]
I consider it as fixed.

**Comment by beatrizmf** [comment]
do it this way:

```
if (typeof window !== 'undefined') {
  Cookie.get('name');
}
```
